//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by InfoManCommon.rc
//
#define IDS_ALERT_UNKNOWN_SERVER_ERROR  501
#define IDS_ALERT_SERVER_FAILURE        502
#define IDS_ALERT_DEVICE_UNSUPPORTED    503
#define IDS_ALERT_MALFORMED_REQUEST     504
#define IDS_ALERT_LOOKUP_LIMIT_REACHED  505
#define IDS_ALERT_INVALID_PROTOCOL_VERSION 506
#define IDS_ALERT_REQUEST_ARGUMENT_MISSING 507
#define IDS_ALERT_UNEXPECTED_REQUEST_ARGUMENT 508
#define IDS_ALERT_INVALID_COOKIE        509
#define IDS_ALERT_USER_DISABLED         510
#define IDS_ALERT_INVALID_REG_CODE      511
#define IDS_ALERT_FORCE_UPGRADE         512
#define IDS_ALERT_INVALID_REQUEST       513
#define IDS_ALERT_MODULE_DOWN           514
#define IDS_ALERT_REG_CODE_EXPIRED      515

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        502
#define _APS_NEXT_COMMAND_VALUE         50001
#define _APS_NEXT_CONTROL_VALUE         2001
#define _APS_NEXT_SYMED_VALUE           501
#endif
#endif
