//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by InfoManCommon.rc
//
#define IDS_APP_TITLE                   1
#define IDC_INFOMAN                     2
#define IDI_INFOMAN                     101
#define IDD_CONNECTION_PROGRESS         102
#define IDR_MAIN_MENU                   102
#define IDS_OK                          103
#define IDS_HELP                        104
#define IDS_MAIN                        105
#define IDS_VIEW                        106
#define IDS_DONE                        107
#define IDS_SEARCH                      108
#define IDS_BACK                        109
#define IDD_ABOUTBOX                    110
#define IDS_UPDATE                      110
#define IDD_ABOUTBOX_WIDE               111
#define IDS_ALERT_UNKNOWN_SERVER_ERROR  501
#define IDS_ALERT_SERVER_FAILURE        502
#define IDD_WEATHER_MAIN                502
#define IDS_ALERT_DEVICE_UNSUPPORTED    503
#define IDR_WEATHER_MENU                503
#define IDD_RECIPES_MAIN                503
#define IDS_ALERT_MALFORMED_REQUEST     504
#define IDD_RECIPES_PREFS               504
#define IDS_ALERT_LOOKUP_LIMIT_REACHED  505
#define IDD_HOROSCOPES_MAIN             505
#define IDS_ALERT_INVALID_PROTOCOL_VERSION 506
#define IDD_BOXOFFICE_MAIN              506
#define IDS_ALERT_REQUEST_ARGUMENT_MISSING 507
#define IDB_RECIPES_LARGE               507
#define IDS_ALERT_UNEXPECTED_REQUEST_ARGUMENT 508
#define IDB_RECIPES_SMALL               508
#define IDS_ALERT_INVALID_COOKIE        509
#define IDB_NONE_SMALL                  509
#define IDS_ALERT_USER_DISABLED         510
#define IDB_NONE_LARGE                  510
#define IDS_ALERT_INVALID_REG_CODE      511
#define IDB_WEATHER_LARGE               511
#define IDR_RECIPES_START               511
#define IDS_ALERT_FORCE_UPGRADE         512
#define IDB_WEATHER_SMALL               512
#define IDS_ALERT_INVALID_REQUEST       513
#define IDB_ABOUT_SMALL                 513
#define IDS_ALERT_MODULE_DOWN           514
#define IDB_ABOUT_LARGE                 514
#define IDS_ALERT_REG_CODE_EXPIRED      515
#define IDB_AMAZON_LARGE                515
#define IDS_ALERT_NOT_ENOUGH_MEMORY     516
#define IDB_AMAZON_SMALL                516
#define IDS_ALERT_MALFORMED_RESPONSE    517
#define IDB_BOXOFFICE_SMALL             517
#define IDS_ALERT_CONNECTION_TIMEOUT    518
#define IDB_BOXOFFICE_LARGE             518
#define IDS_ALERT_NO_RESULTS            519
#define IDB_CURRENCY_LARGE              519
#define IDS_ALERT_LOCATION_UNKNOWN      520
#define IDB_CURRENCY_SMALL              520
#define IDS_ALERT_NOT_IMPLEMENTED       521
#define IDB_DICTIONARY_LARGE            521
#define IDB_DICTIONARY_SMALL            522
#define IDS_ALERT_HOST_UNREACHABLE      522
#define IDB_DREAMS_LARGE                523
#define IDB_DREAMS_SMALL                524
#define IDB_EBAY_LARGE                  525
#define IDB_EBAY_SMALL                  526
#define IDB_EBOOKS_LARGE                527
#define IDB_EBOOKS_SMALL                528
#define IDB_ENCYCLOPEDIA_LARGE          529
#define IDB_ENCYCLOPEDIA_SMALL          530
#define IDB_FLICKR_LARGE                531
#define IDB_FLICKR_SMALL                532
#define IDB_FLIGHTS_LARGE               533
#define IDB_FLIGHTS_SMALL               534
#define IDB_GAS_LARGE                   535
#define IDB_GAS_SMALL                   536
#define IDB_HOROSCOPES_LARGE            537
#define IDB_HOROSCOPES_SMALL            538
#define IDB_JOKES_LARGE                 539
#define IDB_JOKES_SMALL                 540
#define IDB_LISTOFBESTS_LARGE           541
#define IDB_LISTOFBESTS_SMALL           542
#define IDB_LYRICS_LARGE                543
#define IDB_LYRICS_SMALL                544
#define IDB_M411_LARGE                  545
#define IDB_M411_SMALL                  546
#define IDB_MOVIES_LARGE                547
#define IDB_MOVIES_SMALL                548
#define IDB_NETFLIX_LARGE               549
#define IDB_NETFLIX_SMALL               550
#define IDB_QUOTES_LARGE                551
#define IDB_QUOTES_SMALL                552
#define IDB_STOCKS_LARGE                553
#define IDB_STOCKS_SMALL                554
#define IDR_RECIPES_MENU                555
#define IDR_HOROSCOPES_MENU             557
#define IDR_BOXOFFICE_MENU              558
#define IDS_ZODIAC0                     800
#define IDS_ZODIAC1                     801
#define IDS_ZODIAC2                     802
#define IDS_ZODIAC3                     803
#define IDS_ZODIAC4                     804
#define IDS_ZODIAC5                     805
#define IDS_ZODIAC6                     806
#define IDS_ZODIAC7                     807
#define IDS_ZODIAC8                     808
#define IDS_ZODIAC9                     809
#define IDS_ZODIAC10                    810
#define IDS_ZODIAC11                    811
#define IDC_CONNECTION_PROGRESS         2002
#define IDC_PROGRESS_TEXT               2003
#define IDC_PROGRESS_BYTES              2004
#define IDC_WEATHER_SUMMARY             2014
#define IDC_WEATHER_DAYS_LIST           2015
#define IDC_WEATHER_DAY_SELECT          2017
#define IDC_WEATHER_DAY_SPIN            2018
#define IDC_SEARCH_TERM                 2022
#define IDC_RECIPE_NAME                 2023
#define IDC_RECIPE_NOTE                 2024
#define IDC_RECIPE_INGREDIENTS          2025
#define IDC_RECIPE_PREPARATION          2026
#define IDC_RECIPE_REVIEWS              2027
#define IDC_SHOW_RECIPE_GLOBAL_NOTE     2028
#define IDC_RECIPE_GLOBAL_NOTE          2028
#define IDC_LIST                        2029
#define IDC_LIST1                       2032
#define IDM_OK                          40000
#define IDM_HELP                        40001
#define IDM_HELP_ABOUT                  40002
#define IDM_MAIN                        40003
#define IDM_VIEW                        40004
#define ID_MAIN_CHANGELOCATION          50001
#define ID_MAIN_UPDATE                  50002
#define ID_VIEW_DETAILED                50004
#define ID_VIEW_SUMMARY                 50005
#define ID_TEMPERATURE_FAHRENHEIT       50007
#define ID_TEMPERATURE_CELSIUS          50008
#define ID_VIEW_LIST                    50009
#define ID_VIEW_ICONS                   50011
#define ID_VIEW_PREFERENCES             50012
#define ID_VIEW_RECIPE                  50013
#define ID_BACK                         50014
#define ID_SEARCH                       50015
#define ID_VIEW_RECIPES_LIST            50016
#define ID_VIEW_SIGNLIST                50017
#define ID_VIEW_HOROSCOPE               50018
#define ID_VIEW_SIGN_LIST               50019
#define ID_VIEW_UPDATE                  50020
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        559
#define _APS_NEXT_COMMAND_VALUE         50021
#define _APS_NEXT_CONTROL_VALUE         2033
#define _APS_NEXT_SYMED_VALUE           503
#endif
#endif
